electro_project/electro_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('electro/', include('electro_social.urls', namespace='electro')),
    path('electro/', include('django.contrib.auth.urls')),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls')),
    path('groups/', include('groups.urls')),
    # redirect user detail
    path('user/<int:pk>', RedirectView.as_view(
    pattern_name='electro:detail', permanent=False), name='redirect'),
    # notifications system
    path('inbox/notifications/',include(notifications.urls, namespace='notifications')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

electro_project/electro_social/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'electro'

urlpatterns = [
  # auth system
  path('login/', auth_views.LoginView.as_view(
  template_name ='registration/login.html',
  ), name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('signup/', views.SignUp.as_view(), name='signup'),
  path('update_settings/', views.UserEdit.as_view(), name="update_settings"),
  path('password/', views.PasswordChangeView.as_view(
  template_name="registration/change_password.html"
  ), name='password'),
  path('users/', views.ProfileList.as_view(), name='users'),
  path('user/<int:pk>/', views.ProfileDetail.as_view(), name='detail'),
  # user update and delete => user_profile
  path('update/<int:pk>/', views.ProfileUpdate.as_view(),
  name='update'),
  path('user/<int:pk>/delete/', views.ProfileUpdate.as_view(),
  name='delete'),
  path('follow/<int:pk>', views.FollowProfileRedirect.as_view(), name="follow"),
]

electro_project/groups/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = 'groups'

urlpatterns = [
  # group url
  path('create/', views.CreateGroupView.as_view(), name='create'),
  path('list/', views.GroupListView.as_view(), name='list'),
  path('join/<int:pk>', views.JoinGroup.as_view(), name='join'),
  path('leave/<int:pk>', views.LeaveGroup.as_view(), name='leave'),
  path('update/<int:pk>', views.UpdateGroupView.as_view(), name='update'),
  path('delete/<int:pk>', views.DeleteGroupView.as_view(), name='delete'),
  path('detail/<int:pk>', views.MixinDetailAndFormView.as_view(), name='detail'),
  path('user/<int:pk>', RedirectView.as_view(pattern_name='electro:detail'), name='redirect'), 
]

electro_project/posts/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy


from . import views

app_name = 'posts'

urlpatterns = [
  # post list
  path('list/', views.PostListView.as_view(), name="list"),
  # post create
  path('create/', views.CreatePostView.as_view(), name='create'),
  # post update
  path('update/<int:pk>/', views.UpdatePostView.as_view(), name='update'),
  # post delete
  path('delete/<int:pk>/', views.DeletePostView.as_view(), name='delete'),
  # post detail
  path('detail/<int:pk>/', views.PostCommentFormView.as_view(), name='detail'),
  # redirect user detail
  path('user/<int:pk>/', views.RedirectView.as_view(
  pattern_name='electro:detail', permanent=False), name='redirect'),
  # add like on post
  path('like/<int:pk>', views.RedirectAddLike.as_view(), name='like'),
  path('dislike/<int:pk>', views.RedirectAddDislike.as_view(), name='dislike'),
  path('delete/<int:pk>/comment', views.CommentDelete.as_view(),
  name='comment_delete'),
  path('update/<int:pk>/update', views.CommentUpdate.as_view(),
  name='comment_update'),
]

electro_project/electro_project/views.py
from django.views.generic import TemplateView



class IndexView(TemplateView):
    template_name = 'index.html'


class ThanksPage(TemplateView):
    template_name = 'thanks.html'

electro_project/electro_project/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
     <link rel="stylesheet" type="text/css" href="{% static 'css/style_electro.css' %}">
     <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Electro Social</title>
  </head>
  <body>
    {% block page_content %}

    {% endblock %}
  </body>
</html>

electro_project/electro_project/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block page_content %}

<div class="jumbotron">
  <h1 class="display-3">Welcome on Electro Social!</h1>
  <p class="lead">This is a social media where you can meet your friends, groups!</p>
  <hr class="my-4">
  <p>Post about your journey or things who you love and show the world who you are!</p>
  <p class="lead">
    {% if not user.is_authenticated %}
    <a href="{% url 'electro:login' %}" class="btn btn-primary btn-lg" role="button">Login</a>
    <a href="{% url 'electro:signup' %}" class="btn btn-primary btn-lg" role="button">Signup</a>
    {% else %}
    <a href="{% url 'posts:list' %}" class="btn btn-primary btn-lg" role="button">Posts</a>
    <a href="{% url 'groups:list' %}" class="btn btn-primary btn-lg" role="button">Groups</a>
  </p>
  {% endif %}
</div>

{% endblock %}

electro_project/electro_project/templates/thanks.html
{% extends 'base.html' %}
{% block page_content %}


<div class="jumbotron">
  <h1 class="display-3">GoodBye!</h1>
  <p class="lead">You are now logged out</p>
  <hr class="my-4">
  <p>Thanks for your visite, hope to see you later</p>
  <p class="lead">
    <a href="{% url 'electro:login' %}" class="btn btn-primary btn-lg" role="button">Login</a>
    <a href="{% url 'electro:signup' %}" class="btn btn-primary btn-lg" role="button">Signup</a>
</div>


{% endblock %}