electro_project/electro_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('electro/', include('electro_social.urls', namespace='electro')),
    path('electro/', include('django.contrib.auth.urls')),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls')),
    path('groups/', include('groups.urls')),
    # redirect user detail
    path('user/<int:pk>', RedirectView.as_view(
    pattern_name='electro:detail', permanent=False), name='redirect'),
    # notifications system
    path('inbox/notifications/',include(notifications.urls, namespace='notifications')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

electro_project/electro_social/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'electro'

urlpatterns = [
  # auth system
  path('login/', auth_views.LoginView.as_view(
  template_name ='registration/login.html',
  ), name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('signup/', views.SignUp.as_view(), name='signup'),
  path('update_settings/', views.UserEdit.as_view(), name="update_settings"),
  path('password/', views.PasswordChangeView.as_view(
  template_name="registration/change_password.html"
  ), name='password'),
  path('users/', views.ProfileList.as_view(), name='users'),
  path('user/<int:pk>/', views.ProfileDetail.as_view(), name='detail'),
  # user update and delete => user_profile
  path('update/<int:pk>/', views.ProfileUpdate.as_view(),
  name='update'),
  path('user/<int:pk>/delete/', views.ProfileUpdate.as_view(),
  name='delete'),
  path('follow/<int:pk>', views.FollowProfileRedirect.as_view(), name="follow"),
]

electro_project/posts/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy


from . import views

app_name = 'posts'

urlpatterns = [
  # post list
  path('list/', views.PostListView.as_view(), name="list"),
  # post create
  path('create/', views.CreatePostView.as_view(), name='create'),
  # post update
  path('update/<int:pk>/', views.UpdatePostView.as_view(), name='update'),
  # post delete
  path('delete/<int:pk>/', views.DeletePostView.as_view(), name='delete'),
  # post detail
  path('detail/<int:pk>/', views.PostCommentFormView.as_view(), name='detail'),
  # redirect user detail
  path('user/<int:pk>/', views.RedirectView.as_view(
  pattern_name='electro:detail', permanent=False), name='redirect'),
  # add like on post
  path('like/<int:pk>', views.RedirectAddLike.as_view(), name='like'),
  path('dislike/<int:pk>', views.RedirectAddDislike.as_view(), name='dislike'),
  path('delete/<int:pk>/comment', views.CommentDelete.as_view(),
  name='comment_delete'),
  path('update/<int:pk>/update', views.CommentUpdate.as_view(),
  name='comment_update'),
]

electro_project/electro_social/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse_lazy

from PIL import *

class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
    on_delete=models.CASCADE, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='img', blank=True, null=True)
    description = models.TextField(blank=True)
    birth_date = models.DateField(null=True, blank=True)
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True,
    related_name="followers")

    def __str__(self):
        return "@{}".format(self.user)

    class Meta():
        ordering = ['user']

    def get_absolute_url(self):
        return reverse_lazy('electro:detail', kwargs={'pk': self.pk})

electro_project/electro_social/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms

from .models import Profile


class UserCreateForm(UserCreationForm):
    username = forms.CharField(
    widget=forms.TextInput(
    attrs={'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', 'placeholder': 'username'}))
    email = forms.EmailField(widget=(forms.TextInput(
    attrs={'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', 'placeholder': 'email'})))
    password1 = forms.CharField(
    widget=(forms.PasswordInput
    (attrs={'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', 'placeholder': 'password'})))
    password2 = forms.CharField(
    widget=forms.PasswordInput(
    attrs={'class': 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline', 'placeholder': 'repeat password'}))

    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'username'
        self.fields['email'].label = 'email'

class UserUpdateForm(UserChangeForm):
    class Meta:
        fields = ('username', 'email')
        model = User

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['username'].label = 'username'
            self.fields['email'].label = 'email'


class UserInfoForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_picture', 'description', 'birth_date']


class UserProfileSearchForm(forms.Form):
    user = forms.CharField(required=False)

electro_project/electro_social/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import (
FormView,
SingleObjectMixin,
CreateView,
DeleteView,
UpdateView
)
from django.views.generic.list import MultipleObjectMixin
from django.views.generic.base import RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.forms import PasswordChangeForm, UserChangeForm
from django.utils import timezone
from django.http import HttpResponseForbidden
from django.contrib.auth.models import User
from django.db import models
from django.db.models import F
from django.contrib import messages
from .forms import (
UserCreateForm,
UserInfoForm,
UserProfileSearchForm,
UserUpdateForm
)
from .models import Profile

from posts.models import Post, Comment
from groups.models import Group


class SignUp(CreateView):
    form_class = UserCreateForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')


class UserEdit(UpdateView):
    form_class = UserUpdateForm
    template_name = 'registration/update_user.html'
    success_url = reverse_lazy('posts:list')

    def get_object(self):
        return self.request.user

class PasswordChangeView(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('login')


class ProfileList(ListView):
    model = Profile
    form_class = UserProfileSearchForm
    template_name = 'profiles/profile_list.html'
    context_object_name = 'infos'

    def get_queryset(self):
        form = self.form_class(self.request.GET)
        if form.is_valid():
            return Profile.objects.filter(
            user__username__icontains=form.cleaned_data['user']
            )
        return Profile.objects.all()


class ProfileDetail(DetailView):
    template_name = 'profiles/profile_detail.html'

    def get_object(self):
        return Profile.objects.filter(user=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(ProfileDetail, self).get_context_data(**kwargs)
        context['infos'] = self.get_object() # profile
        context['posts'] = Post.objects.all().filter(user=self.kwargs['pk'])
        context['post_numbers'] = Post.objects.filter(user=self.kwargs['pk']).count()
        context['groups'] = Group.objects.filter(members=self.kwargs['pk'])
        return context


class ProfileUpdate(UpdateView):
    template_name = 'profiles/profile_update.html'
    model = Profile
    fields = ['description', 'profile_picture']

    def form_valid(self, form):
        if self.request.method == "POST":
            obj = get_object_or_404(Profile, pk=self.kwargs['pk'])
            form = UserInfoForm(self.request.POST, instance=obj)
            if form.is_valid():
                form.save(commit=True)
        return super(ProfileUpdate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy("electro:detail", kwargs={'pk': self.kwargs.get('pk')})


class ProfileDelete(DeleteView):
    model = Profile
    success_url = reverse_lazy('profiles/profile_list.html')


class FollowProfileRedirect(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('electro:detail', kwargs=
        {'pk': self.kwargs.get('pk')})

    def get(self, request, *args, **kwargs):
        if self.request.method == "POST":
            my_profile = Profile.objects.get(user=self.request.user)
            pk = request.POST.get('pk')
            obj = Profile.objects.get(pk=pk)
            if obj.user in my_profile.followers.all():
                my_profile.followers.remove(obj.user)
                messages.success(request, 'WOW you are unfollowing {}'.format(
                my_profile.user))
            else:
                my_profile.followers.add(obj.user)
                messages.success(request, 'WOW you are following {}'.format(
                my_profile.user))
        return super(FollowProfileRedirect, self).get(request, *args, **kwargs)

electro_project/electro_social/templates/profiles/profile_detail.html
{% extends 'base.html' %}

{% load static %}

{% block page_content %}
{% if user.is_authenticated %}
<div class="padding">
	<div class="container">
		<div class="card">
			{% for info in infos %}
			{% if info.profile_picture %}
			<img class="card-image-top" src="{{ info.profile_picture.url }}" id="profile-picture">
			{% else %}
			<img class="card-image-top" src="{% static '/img/no-profile.jpg' %}" id="profile-picture">
			{% endif %}
			<h1 class="card-title"> Profile's name: {{ info.user }} </h1>
			<p>{{ info.description }}</p>
			{% if info.followers %}
			<h4>Followers</h4>
			<p>{{ info.followers.count }}</p>
			{% else %}
			<p>No follower</p>
			{% endif %}
			<a href="{% url 'electro:follow' user.pk %}">Follow</a>
		</div>
	</div>
</div>
<div class="container">
	{% endfor %}
          {%  for post in posts  %}
              {% if forloop.counter0|divisibleby:3 %} <div class="row text-center"> {%  endif %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-content">
													<h4 class="card-header"><a href="{% url 'posts:detail' post.pk %}">{{ post.title }}</a></h4>
													<p class="card-text">{{ post.content }}</p>
													<p class="card-text">{{ post.date_post }}</p>
                        </div>
                    </div>
                </div>
          {%  if forloop.counter|divisibleby:3 or forloop.last %}</div><hr>{%  endif %}
          {%  endfor %}
        </div>
				{% endif %}
{% endblock %}

electro_project/electro_social/templates/profiles/profile_form.html
{% extends 'base.html' %}


{% block page_content %}

{% if user.is_authenticated %}

<div class="padding">
<div class="container">
  <form  method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn btn-primary" value="user_form">
  </form>
</div>
</div>

{% endif %}

{% endblock %}

electro_project/electro_social/templates/profiles/profile_list.html
{% extends 'base.html' %}
{% load static %}
{% block page_content %}
<div class="container" id="padding">
  <form method="GET">
    {{ form }}
    <input id="user" type="text" name="user">
  </form>
</div>
<div class="container">
  {%  for info in infos  %}
  {% if forloop.counter0|divisibleby:3 %} <div class="row text-center"> {%  endif %}
    <div class="col-md-4">
      <div class="card">
        {% if info.profile_picture %}
        <img class="card-image-top" src="{{ info.profile_picture.url }}" id="profile-picture">
        {% else %}
        <img class="card-image-top" src="{% static '/img/no-profile.jpg' %}" id="profile-picture">
        {% endif %}
        <div class="card-content">
          <br>
          <h4><a href="{% url 'electro:detail' info.user.pk %}">{{ info.user }}</a></h4>
          <hr>
          <p>{{ info.description }}</p>
          <br>
        </div>
      </div>
    </div>
    {%  if forloop.counter|divisibleby:3 or forloop.last %}</div><hr>{%  endif %}
    {%  endfor %}
  </div>
{% endblock %}

electro_project/electro_social/templates/profiles/profile_update.html
{% load static %}
{% block page_content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}