electro_project/electro_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('electro/', include('electro_social.urls', namespace='electro')),
    path('electro/', include('django.contrib.auth.urls')),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls')),
    path('groups/', include('groups.urls')),
    # redirect user detail
    path('user/<int:pk>', RedirectView.as_view(
    pattern_name='electro:detail', permanent=False), name='redirect'),
    # notifications system
    path('inbox/notifications/',include(notifications.urls, namespace='notifications')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

electro_project/electro_social/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'electro'

urlpatterns = [
  # auth system
  path('login/', auth_views.LoginView.as_view(
  template_name ='registration/login.html',
  ), name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('signup/', views.SignUp.as_view(), name='signup'),
  path('update_settings/', views.UserEdit.as_view(), name="update_settings"),
  path('password/', views.PasswordChangeView.as_view(
  template_name="registration/change_password.html"
  ), name='password'),
  path('users/', views.ProfileList.as_view(), name='users'),
  path('user/<int:pk>/', views.ProfileDetail.as_view(), name='detail'),
  # user update and delete => user_profile
  path('update/<int:pk>/', views.ProfileUpdate.as_view(),
  name='update'),
  path('user/<int:pk>/delete/', views.ProfileUpdate.as_view(),
  name='delete'),
  path('follow/<int:pk>', views.FollowProfileRedirect.as_view(), name="follow"),
]

electro_project/posts/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy


from . import views

app_name = 'posts'

urlpatterns = [
  # post list
  path('list/', views.PostListView.as_view(), name="list"),
  # post create
  path('create/', views.CreatePostView.as_view(), name='create'),
  # post update
  path('update/<int:pk>/', views.UpdatePostView.as_view(), name='update'),
  # post delete
  path('delete/<int:pk>/', views.DeletePostView.as_view(), name='delete'),
  # post detail
  path('detail/<int:pk>/', views.PostCommentFormView.as_view(), name='detail'),
  # redirect user detail
  path('user/<int:pk>/', views.RedirectView.as_view(
  pattern_name='electro:detail', permanent=False), name='redirect'),
  # add like on post
  path('like/<int:pk>', views.RedirectAddLike.as_view(), name='like'),
  path('dislike/<int:pk>', views.RedirectAddDislike.as_view(), name='dislike'),
  path('delete/<int:pk>/comment', views.CommentDelete.as_view(),
  name='comment_delete'),
  path('update/<int:pk>/update', views.CommentUpdate.as_view(),
  name='comment_update'),
]

electro_project/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse_lazy

from electro_social.models import Profile

from groups.models import Group


class Post(models.Model):
    title = models.CharField(max_length=40)
    content = models.TextField()
    post_img = models.ImageField(upload_to='img', blank=True, null=True)
    date_post = models.DateTimeField('date published',auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
    on_delete=models.CASCADE)
    like = models.ManyToManyField(User, related_name='likes',
    blank=True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE,
    blank=True, null=True)

    def __str__(self):
        return "{}, {}".format(self.user, self.title)

    class Meta:
        ordering = ['date_post']

    def get_absolute_url(self):
        return reverse_lazy('detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True,
    null=True)
    title = models.CharField(max_length=30)
    comment = models.TextField()
    date_post = models.DateTimeField('date published',auto_now_add=True)
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL,
    on_delete=models.CASCADE, blank=True, null=True)
    like = models.ManyToManyField(User, related_name='comment_like',
    blank=True)

    def __str__(self):
        return "{}, {}".format(self.from_user, self.title)

    class Meta:
        ordering = ['title']

    def get_absolute_url(self):
        return reverse_lazy('detail', kwargs={'pk': self.pk})

electro_project/posts/forms.py
from django.forms import ModelForm
from django import forms
from .models import Comment, Post


class UserPostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

        widgets= {
        'title': forms.TextInput(attrs={'class': 'form-control'}),
        'content': forms.Textarea(attrs={'class': 'form-control'}),
        }


class UserCommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['title', 'comment']
        exclude = ['group']

        widgets = {
        'title': forms.TextInput(attrs={'class': 'form-control'}),
        'comment': forms.Textarea(attrs={'class': 'form-control'}),
        }

electro_project/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.views.generic import TemplateView, ListView, View
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import FormView, SingleObjectMixin, FormMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseForbidden, Http404, HttpResponseRedirect
from django.shortcuts import reverse
from django.views.generic.base import RedirectView

from .forms import UserCommentForm, UserPostForm
from .models import Post, Comment

from electro_social.views import ProfileDetail
from electro_social.models import Profile


class PostListView(ListView):
    template_name = 'logged/post_list.html'
    context_object_name = 'posts'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(date_post__lte=timezone.now()).order_by(
                '-date_post')

    def get_success_url(self):
        return reverse_lazy('posts:detail')


class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = 'electro/login'
    template_name = 'logged/create_post.html'
    form_class = UserPostForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        pk = self.kwargs.get("post_pk", None)
        form.instance.post = pk
        if form.is_valid():
            form.save()
            return super(CreatePostView, self).form_valid(form)

    def get_success_url(self):
        return reverse("posts:detail", kwargs={'pk': self.object.pk})


class UpdatePostView(LoginRequiredMixin, UpdateView):
    login_url = 'electro/login'
    template_name = 'logged/post_update.html'
    form_class = UserPostForm
    model = Post

    def get_object(self, queryset=None):
        return Post.objects.filter(pk=self.kwargs['pk']).first()

    # filter if the current user is the author
    def get_queryset(self):
        queryset = super(UpdatePostView, self).get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            return super(UpdatePostView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('posts:detail', kwargs={'pk': self.object.pk})


# => Delete Post
class DeletePostView(LoginRequiredMixin, DeleteView):
    template_name = 'logged/post_delete.html'
    context_object_name = 'post'
    model = Post

    def get_object(self, queryset=None):
        return Post.objects.filter(pk=self.kwargs['pk']).first()

    def get_queryset(self):
        queryset = super(DeletePostView, self).get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset

    def get_success_url(self):
        return reverse_lazy('posts:list')


# 3 part => Mixed views
# 1 part => detail view with context data for forms and comments
class PostDetailView(DetailView):
    template_name = 'logged/post_detail.html'
    model = Post
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        comments = Comment.objects.filter(post=self.kwargs['pk'])
        context['comments'] = comments
        context['form'] = UserCommentForm()
        return context


# 2 part => Form view for comments
class CommentFormView(LoginRequiredMixin, SingleObjectMixin, FormView):

    template_name = 'logged/post_detail.html'
    model = Comment
    form_class = UserCommentForm

    def get_object(self):
        return get_object_or_404(Post, pk=self.kwargs['pk'])

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.from_user = self.request.user
        form.instance.post = self.get_object()
        if form.is_valid():
            form.save()
            return super(CommentFormView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy("posts:detail", kwargs={'pk': self.kwargs['pk']})


# part 3 => this is where we send both view in one
class PostCommentFormView(View):

    def get(self, request, *args, **kwargs):
        view = PostDetailView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentFormView.as_view()
        return view(request, *args, **kwargs)


# like redirect suppose to be redirect to detail post which was liked
class RedirectAddLike(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('posts:detail', kwargs=
        {'pk': self.kwargs.get('pk')})


    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, id=request.POST.get('post_id'))
        post.like.add(self.request.user)
        return super(RedirectAddLike, self).get(request, *args, **kwargs)


class RedirectAddDislike(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('posts:detail', kwargs=
                            {'pk': self.kwargs.get('pk')})

    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, id=request.POST.get('post_id'))
        post.like.remove(self.request.user)
        return super(RedirectAddDislike, self).get(request, *args, **kwargs)


class CommentDelete(DeleteView):
    template_name = 'logged/comment_delete.html'
    context_object_name = 'comment'
    model = Comment

    def get_object(self, queryset=None):
        return Comment.objects.filter(pk=self.kwargs['pk']).first()

    def get_queryset(self):
        queryset = super(CommentDelete, self).get_queryset()
        queryset = queryset.filter(from_user=self.request.user)
        return queryset

    def get_success_url(self):
        return reverse_lazy('posts:detail', kwargs={'pk': self.object.pk})


class CommentUpdate(UpdateView):
    template_name = 'logged/comment_update.html'
    form_class = UserCommentForm
    model = Comment

    def get_object(self, queryset=None):
        return Comment.objects.filter(pk=self.kwargs['pk']).first()

        # filter if the current user is the author
    def get_queryset(self):
        queryset = super(CommentUpdate, self).get_queryset()
        queryset = queryset.filter(from_user=self.request.user)
        return queryset

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            return super(CommentUpdate, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('posts:detail', kwargs={'pk': self.object.pk})

electro_project/posts/templates/logged/comment_delete.html
{% extends 'base.html' %}
{% block page_content %}
{% if user.is_authenticated %}

<form method="POST">
  {% csrf_token %}
  <p> Are you sure you want to delete "{{ comment }}?"</p>
  <input type="submit" value="Comfirm">
{% else %}
<div class="container text-center">
  <a class="btn btn-primary" href="{% url 'electro:signup' %}">SignUp</a>
  <a class="btn btn-primary" href="{% url 'electro:login' %}">Connect</a>
</div>

{% endif %}
{% endblock %}

electro_project/posts/templates/logged/comment_form.html
{% extends 'base.html' %}
{% block page_content %}
{% if user.is_authenticated %}
<div class="container">
  <form  method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn btn-primary" value="comment">
  </form>
</div>
{% else %}
<div class="container text-center">
  <a class="btn btn-primary" href="{% url 'electro:signup' %}">SignUp</a>
  <a class="btn btn-primary" href="{% url 'electro:login' %}">Connect</a>
</div>
{% endif %}
{% endblock %}

electro_project/posts/templates/logged/comment_update.html
{% extends 'base.html' %}

{% block page_content %}
{% if user.is_authenticated %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Delete">
</form>
{% else %}
<div class="container text-center">
  <a class="btn btn-primary" href="{% url 'electro:signup' %}">SignUp</a>
  <a class="btn btn-primary" href="{% url 'electro:login' %}">Connect</a>
</div>
{% endif %}
{% endblock %}

electro_project/posts/templates/logged/create_post.html
{% extends 'base.html' %}


{% block page_content %}
<div class="container">
<form method="POST"> {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>
</div>
{% endblock %}

electro_project/posts/templates/logged/post_delete.html
{% extends 'base.html' %}
{% block page_content %}
{% if user.is_authenticated %}

<form method="POST">
  {% csrf_token %}
  <p> Are you sure you want to delete "{{ post }}?"</p>
  <input type="submit" value="Comfirm">
{% else %}
<div class="container text-center">
  <a class="btn btn-primary" href="{% url 'electro:signup' %}">SignUp</a>
  <a class="btn btn-primary" href="{% url 'electro:login' %}">Connect</a>
</div>

{% endif %}
{% endblock %}

electro_project/posts/templates/logged/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block page_content %}
{% if post.user_id == user.pk %}
<div class="container">
  <a href="{% url 'posts:update' pk=post.pk %}">Update</a>
  <a href="{% url 'posts:delete' pk=post.pk %}">Delete</a>
</div>
{% endif %}
<div class="container">
  <h1> {{ post.title }} </h1>
  <ul>
    <li>{{ post.content }}</li>
    <li>{{ post.date_post }}</li>
    <li>{{ post.user }}</li>
    <li>Like: {{ post.like.count }}</li>
  </ul>
</div>
<div class="container">
  <ul>
    {% for comment in comments %}
    <li>{{ comment.title }}</li>
    <li>{{ comment.comment }}</li>
    <li><a href="{% url 'posts:redirect' comment.from_user.pk %}">{{ comment.from_user }}</a></li>
    <li>{{ comment.date_post }}</li>
  </ul>
  {% if post.user_id == user.pk %}
  <div class="container">
    <a href="{% url 'posts:comment_delete' pk=comment.pk %}">Delete</a>
    <a href="{% url 'posts:comment_update' pk=comment.pk %}">Update</a>
  </div>
  {% endif %}
  {% endfor %}
</div>
<div class="container">
  <form action="{% url 'posts:detail' post.pk %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn btn-primary" value="comment">
  </form>
</div>
{% block like_dislike %}
<div class="container">
	<p>
    <form action="{% url 'posts:like' post.pk %}" method="POST">
      {% csrf_token %}
      <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-primary">Like
      </button>
    </form>
  </p>
  <p>
    <form action="{% url 'posts:dislike' post.pk %}" method="POST">
      {% csrf_token %}
      <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-primary">Dislike
      </button>
    </form>
  </p>
</div>
{% endblock %}
{% endblock %}

electro_project/posts/templates/logged/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block page_content %}
{% if user.is_authenticated %}
<div class="padding">
  <div class="container">
    <a class="btn btn-primary" href="{% url 'posts:create' %}">Create</a>
  </div>
</div>

{% else %}
<div class="padding">
<div class="container">
  <a href="{% url 'electro:login' %}" class="btn btn-primary">Login</a>
  <a href="{% url 'electro:signup' %}" class="btn btn-primary">SignUp</a>
 </div>
</div>
{% endif %}
<div class="container">
  {% load post_extras %}
  {%  for post in posts|cut %}
  {% if forloop.counter0|divisibleby:3 %} <div class="row text-center"> {%  endif %}
    <div class="col-md-4">
      <div class="card">
        <div class="card-content">
          <br>
          <h4 class="card-title"><a href="{% url 'posts:detail' post.pk %}">{{ post.title }}</a></h4>
          <hr>
          <p class="card-text">{{ post.content }}</p>
          <p>{{ post.date_post }}</p>
          <p><a href="{% url 'posts:redirect' post.user.pk %}">from: @{{ post.user }}</a></p>
          <br>
          <p>
            <form action="{% url 'posts:like' post.pk %}" method="POST">
              {% csrf_token %}
              <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-primary">Like
              </button>
            </form>
          </p>
          <p>
            <form action="{% url 'posts:dislike' post.pk %}" method="POST">
              {% csrf_token %}
              <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-primary">Dislike
              </button>
            </form>
          </p>
          <p>Like: {{ post.like.count }}</p>
        </div>
      </div>
    </div>
    {%  if forloop.counter|divisibleby:3 or forloop.last %}</div><hr>{%  endif %}
    {%  endfor %}
  </div>
{% endblock %}

electro_project/posts/templates/logged/post_update.html
{% extends 'base.html' %}

{% block page_content %}
{% if user.is_authenticated %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>
{% else %}
<div class="container text-center">
  <a class="btn btn-primary" href="{% url 'electro:signup' %}">SignUp</a>
  <a class="btn btn-primary" href="{% url 'electro:login' %}">Connect</a>
</div>
{% endif %}
{% endblock %}