electro_project/electro_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
import notifications.urls

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('electro/', include('electro_social.urls', namespace='electro')),
    path('electro/', include('django.contrib.auth.urls')),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls')),
    path('groups/', include('groups.urls')),
    # redirect user detail
    path('user/<int:pk>', RedirectView.as_view(
    pattern_name='electro:detail', permanent=False), name='redirect'),
    # notifications system
    path('inbox/notifications/',include(notifications.urls, namespace='notifications')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

electro_project/electro_social/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views


app_name = 'electro'

urlpatterns = [
  # auth system
  path('login/', auth_views.LoginView.as_view(
  template_name ='registration/login.html',
  ), name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('signup/', views.SignUp.as_view(), name='signup'),
  path('update_settings/', views.UserEdit.as_view(), name="update_settings"),
  path('password/', views.PasswordChangeView.as_view(
  template_name="registration/change_password.html"
  ), name='password'),
  path('users/', views.ProfileList.as_view(), name='users'),
  path('user/<int:pk>/', views.ProfileDetail.as_view(), name='detail'),
  # user update and delete => user_profile
  path('update/<int:pk>/', views.ProfileUpdate.as_view(),
  name='update'),
  path('user/<int:pk>/delete/', views.ProfileUpdate.as_view(),
  name='delete'),
  path('follow/<int:pk>', views.FollowProfileRedirect.as_view(), name="follow"),
]

electro_project/groups/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

app_name = 'groups'

urlpatterns = [
  # group url
  path('create/', views.CreateGroupView.as_view(), name='create'),
  path('list/', views.GroupListView.as_view(), name='list'),
  path('join/<int:pk>', views.JoinGroup.as_view(), name='join'),
  path('leave/<int:pk>', views.LeaveGroup.as_view(), name='leave'),
  path('update/<int:pk>', views.UpdateGroupView.as_view(), name='update'),
  path('delete/<int:pk>', views.DeleteGroupView.as_view(), name='delete'),
  path('detail/<int:pk>', views.MixinDetailAndFormView.as_view(), name='detail'),
  path('user/<int:pk>', RedirectView.as_view(pattern_name='electro:detail'), name='redirect'), 
]

electro_project/posts/urls.py
from django.urls import path
from django.conf.urls import url
from django.views.generic.base import RedirectView
from django.urls import reverse_lazy


from . import views

app_name = 'posts'

urlpatterns = [
  # post list
  path('list/', views.PostListView.as_view(), name="list"),
  # post create
  path('create/', views.CreatePostView.as_view(), name='create'),
  # post update
  path('update/<int:pk>/', views.UpdatePostView.as_view(), name='update'),
  # post delete
  path('delete/<int:pk>/', views.DeletePostView.as_view(), name='delete'),
  # post detail
  path('detail/<int:pk>/', views.PostCommentFormView.as_view(), name='detail'),
  # redirect user detail
  path('user/<int:pk>/', views.RedirectView.as_view(
  pattern_name='electro:detail', permanent=False), name='redirect'),
  # add like on post
  path('like/<int:pk>', views.RedirectAddLike.as_view(), name='like'),
  path('dislike/<int:pk>', views.RedirectAddDislike.as_view(), name='dislike'),
  path('delete/<int:pk>/comment', views.CommentDelete.as_view(),
  name='comment_delete'),
  path('update/<int:pk>/update', views.CommentUpdate.as_view(),
  name='comment_update'),
]

electro_project/groups/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from electro_social.models import Profile


class Group(models.Model):
    title = models.CharField(max_length=30)
    description = models.TextField()
    members = models.ManyToManyField(User, blank=True, through='Member')
    banner = models.ImageField(upload_to='img', blank=True, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
    on_delete=models.CASCADE, blank=True, null=True, related_name='owner')

    def __str__(self):
        return "{}, title: {}".format(self.owner, self.title)

    def get_absolute_url(self):
        return reverse_lazy('detail', kwargs={'pk': self.pk})


class Member(models.Model):
    group = models.ForeignKey(Group, related_name="memberships",
    on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="user_groups",
    on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.user)

    class Meta:
        unique_together = ("group", "user")

electro_project/groups/forms.py
from .models import Group
from django import forms

from django.forms import ModelForm

from posts.models import Post

class GroupFrom(ModelForm):
    class Meta:
        model = Group
        fields = ['title', 'description']

        widgets= {
        'title': forms.TextInput(attrs={'class': 'form-control'}),
        'description': forms.Textarea(attrs={'class': 'form-control'}),
        }


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

        widgets= {
        'title': forms.TextInput(attrs={'class': 'form-control'}),
        'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

electro_project/groups/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, RedirectView
from django.views.generic.edit import (CreateView, UpdateView, DeleteView,
FormView, SingleObjectMixin)
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.forms.models import inlineformset_factory

from .forms import GroupFrom, PostForm
from .models import Group, Member

from django.contrib.auth.models import User
from electro_social.models import Profile

from posts.models import Post


# List of group
class GroupListView(ListView):

    template_name = 'group/index_group.html'
    model = Group
    context_object_name = 'groups'

    def get_success_url(self):
        return reverse_lazy('groups:detail')


# group detail with context data for add post in group
class GroupDetailView(DetailView):

    model = Group
    template_name = 'group/detail_group.html'
    context_object_name = 'group'

    def get_context_data(self, **kwargs):
        context = super(GroupDetailView, self).get_context_data(**kwargs)
        context['form'] = PostForm()
        context['postgroup'] = Post.objects.filter(group=self.kwargs['pk'])
        return context


# Post in group
class PostGroupFormView(LoginRequiredMixin, SingleObjectMixin, FormView):

    model = Post
    form_class = PostForm
    template_name = 'group/detail_group.html'

    def get_object(self):
        return get_object_or_404(Group, pk=self.kwargs.get('pk'))

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        form = PostForm()
        if self.request.method == "POST":
            form = PostForm(self.request.POST)
            if form.is_valid():
                form.save(commit=False)
                form.instance.group = self.get_object()
                form.instance.user = self.request.user
                form.save(commit=True)
        return super(PostGroupFormView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('groups:detail', kwargs={'pk': self.object.pk})


class MixinDetailAndFormView(View):

    def get(self, request, *args, **kwargs):
        view = GroupDetailView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = PostGroupFormView.as_view()
        return view(request, *args, **kwargs)


# create group view
class CreateGroupView(CreateView):

    form_class = GroupFrom
    model = Group
    template_name = 'group/create_group.html'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        if form.is_valid():
            form.save()
        return super(CreateGroupView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('groups:detail', kwargs={'pk': self.object.pk})


# Join Group view
class JoinGroup(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('groups:detail', kwargs=
        {'pk': self.kwargs.get('pk')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, pk=self.kwargs.get('pk'))
        if not Member.objects.filter(group=group, user=self.request.user):
            obj, created = Member.objects.get_or_create(user=self.request.user,
            group=group)
            if created:
                messages.success(request, 'You are now a member')
        else:
            messages.add_message(request, messages.INFO, 'You are already a member')
        return super(JoinGroup, self).get(request, *args, **kwargs)


# leave group redirectview
class LeaveGroup(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('groups:detail',
                            kwargs={'pk': self.kwargs.get('pk')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, pk=self.kwargs.get('pk'))
        delete_member = Member.objects.filter(
        user=self.request.user, group=group).delete()
        if delete_member:
            messages.success(request, 'You leave the group')
        return super(LeaveGroup, self).get(request, *args, **kwargs)


# update group view
class UpdateGroupView(UpdateView):
    template_name = 'group/update_group.html'
    model = Group
    form_class = GroupFrom

    def get_success_url(self):
        return reverse_lazy('groups:detail', kwargs={'pk': self.object.pk})


# delete view
class DeleteGroupView(DeleteView):
    template_name = 'group/delete_group.html'
    model = Group
    success_url = reverse_lazy('groups:list')

electro_project/groups/templates/group/create_group.html
{% extends 'base.html' %}

{% block page_content %}

<div class="container">
<form method="POST"> {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>
</div>

{% endblock %}

electro_project/groups/templates/group/delete_group.html
{% extends 'base.html' %}

{% block page_content %}

<form method="POST">
  {% csrf_token %}
  <p> Are you sure you want to delete "{{ group }}?"</p>
  <input type="submit" value="Comfirm">

{% endblock %}

electro_project/groups/templates/group/detail_group.html
{% extends 'base.html' %}

{% block page_content %}

{% if group.owner == request.user %}   
<div class="container">
  <a href="{% url 'groups:update' pk=group.pk %}">Update Group</a>
</div>
<div class="container">
  <a href="{% url 'groups:delete' pk=group.pk %}">Delete Group</a>
</div>
{% endif %}

<div class="container">
  <h1>{{ group.title }}</h1>
  <ul>
    <li>{{ group.description }}</li>
    <li>{{ group.members.count }}</li>
    <li><a href="{% url 'groups:redirect' group.owner.pk %}">{{ group.owner }}</a></li>
  </ul>
</div>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% if user.is_authenticated %}
<div class="container-fluid">
  <a class="btn btn-primary" href="{% url 'groups:join' pk=group.pk %}">Join</a>
</div>

<div class="container-fluid">
  <a class="btn btn-primary" href="{% url 'groups:leave' pk=group.pk %}">Leave</a>
</div>

{% else %}
<div class="container">
  <h3> Login or Signup</h3>
  <h4>You must be login for join a group</h4>
  <a href="{% url 'electro:login'  %}">Login</a>
  <a href="{% url 'electro:signup'  %}">Register</a>
{% endif %}


<div class="container" id="padding">
 <form method="POST" action="{% url 'groups:detail' group.pk %}">
    {% csrf_token %}
    {{ form }}
    <button type="submit" name="" value="">Submit</button>
  </form>
</div>


<div class="container" id="padding">
            {%  for post in postgroup %}
                {% if forloop.counter0|divisibleby:3 %} <div class="row text-center"> {%  endif %}
                  <div class="col-md-4">
                      <div class="card">
                          <div class="card-content">
                              <h4 class="card-title"><a href="{% url 'posts:detail' post.pk %}">{{ post.title }}</a></h4>
                               <p class="card-text">{{ post.content }}</p>
                               <p><a href="{% url 'groups:redirect' post.user.pk %}">{{ post.user }}</a></p>
                               <p>{{ post.date_post }}</p>
                               <form action="{% url 'posts:like' post.pk %}" method="POST">
                        		    {% csrf_token %}
                        		    <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-primary">
                        			    Like
                        		    </button>
                         	     </form>
                               <form action="{% url 'posts:dislike' post.pk %}" method="POST">
                       		    {% csrf_token %}
                       		    <button type="submit" name="post_id" value="{{ post.id }}" class="btn btn-primary">
                       			    Dislike
                       		    </button>
                        	    </form>
                          </div>
                      </div>
                  </div>
            {%  if forloop.counter|divisibleby:3 or forloop.last %}</div><!-- row closing --><hr>{%  endif %}
            {%  endfor %}
         </div>


{% endblock %}

electro_project/groups/templates/group/index_group.html
{% extends 'base.html' %}


{% block page_content %}

<div class="container">
  <button class="btn btn-success">
  <a href="{% url 'groups:create' %}">Create Group</a>
</button>
<div class="container">
  {%  for group in groups  %}
  {% if forloop.counter0|divisibleby:3 %} <div class="row text-center"> {%  endif %}
    <div class="col-md-4">
      <div class="card">
        <div class="card-content">
          <br>
          <h4 class="card-header"><a href="{% url 'groups:detail' group.pk %}">{{ group.title }}</a></h4>
          <hr>
          <p class="card-text">{{ group.description }}<p>
            <p>Number of members: {{ group.members.count }}</p>
            <p class="card-footer"><a href="{% url 'groups:redirect' group.owner.pk %}">Owner: {{ group.owner }}</a></p>
            <br>
          </div>
        </div>
      </div>
      {%  if forloop.counter|divisibleby:3 or forloop.last %}</div><hr>{%  endif %}
      {%  endfor %}
    </div>
{% endblock %}

electro_project/groups/templates/group/update_group.html
{% extends 'base.html' %}
{% block page_content %}
<div class="container">
  <form method="POST"> {% csrf_token %}
  {{ form.as_p }}
  <input value="submit">
</form>
</div>
{% endblock %}